//Doctor Actions
export const SEARCH_DOCTOR = 'SEARCH_DOCTOR'
export const LOAD_DOCTORS = 'LOAD_DOCTORS'
export const LOADING_DOCTORS = 'LOADING_DOCTORS'
export const DOCTORS_FAILED = 'DOCTORS_FAILED'
export const ADD_DOCTOR = "ADD_DOCTOR"
export const ADD_DOCTOR_FAILED = "ADD_DOCTOR_FAILED"
export const DELETE_DOCTOR = "DELETE_DOCTOR"
export const OPEN_DOCTOR_DIALOG = "OPEN_DOCTOR_DIALOG"
export const CLOSE_DOCTOR_DIALOG = "CLOSE_DOCTOR_DIALOG"
export const CLOSE_DOCTOR_FAILED_DIALOG = "CLOSE_DOCTOR_FAILED_DIALOG"
export const DOCTOR_USERNAME_IS_VALID = "DOCTOR_USERNAME_IS_VALID" 
export const DOCTOR_USERNAME_IS_NOT_VALID = "DOCTOR_USERNAME_IS_NOT_VALID" 
export const DOCTOR_EMAIL_IS_VALID = "DOCTOR_EMAIL_IS_VALID" 
export const DOCTOR_EMAIL_IS_NOT_VALID = "DOCTOR_EMAIL_IS_NOT_VALID" 
export const CLEAR_DOCTOR_REGISTER_ERROR_MESSAGES = 'CLEAR_DOCTOR_REGISTER_ERROR_MESSAGES'

export const LOAD_CLINICS = 'LOAD_CLINICS'
export const LOADING_CLINICS = 'LOADING_CLINIC'
export const CLINICS_FAILED = 'CLINICS_FAILED'
export const ADD_CLINIC = "ADD_CLINIC"
export const DELETE_CLINIC = "DELETE_CLINIC"
export const OPEN_CLINIC_DIALOG = "OPEN_CLINIC_DIALOG"
export const CLOSE_CLINIC_DIALOG = "CLOSE_CLINIC_DIALOG"
export const CLOSE_CLINIC_FAILED_DIALOG = "CLOSE_CLINIC_FAILED_DIALOG"
export const ADD_CLINIC_FAILED = "ADD_CLINIC_FAILED"


export const LOAD_PATIENTS = 'LOAD_PATIENTS'
export const LOADING_PATIENTS = 'LOADING_PATIENTS'
export const PATIENTS_FAILED = 'PATIENTS_FAILED'
export const ADD_PATIENT = "ADD_PATIENT"
export const ADD_PATIENT_FAILED = "ADD_PATIENT_FAILED"
export const DELETE_PATIENT = "DELETE_PATIENT"
export const OPEN_PATIENT_DIALOG = "OPEN_PATIENT_DIALOG"
export const CLOSE_PATIENT_DIALOG = "CLOSE_PATIENT_DIALOG"
export const CLOSE_PATIENT_FAILED_DIALOG = "CLOSE_PATIENT_FAILED_DIALOG"
export const PATIENT_USERNAME_IS_VALID = "PATIENT_USERNAME_IS_VALID" 
export const PATIENT_USERNAME_IS_NOT_VALID = "PATIENT_USERNAME_IS_NOT_VALID" 
export const PATIENT_EMAIL_IS_VALID = "PATIENT_EMAIL_IS_VALID" 
export const PATIENT_EMAIL_IS_NOT_VALID = "PATIENT_EMAIL_IS_NOT_VALID" 


export const LOAD_APPOINTMENTS = 'LOAD_APPOINTMENTS'
export const LOADING_APPOINTMENTS = 'LOADING_APPOINTMENTS'
export const APPOINTMENTS_FAILED = 'APPOINTMENTS_FAILED'
export const ACCEPT_APPOINTMENT = "ACCEPT_APPOINTMENT"
export const ADD_APPOINTMENT = "ADD_APPOINTMENT"
export const UPDATE_APPOINTMETNS = "UPDATE_APPOINTMETNS"
export const LOAD_ACCEPTED_APPOINTMENTS = "LOAD_ACCEPTED_APPOINTMENTS"
export const LOAD_ACCEPTED_APPOINTMENTS_FAILED = "LOAD_ACCEPTED_APPOINTMENTS"
export const LOAD_ACCEPTED_APPOINTMENT_FAILED = "LOAD_ACCEPTED_APPOINTMENT_FAILED"
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT"
export const CLEAR_ACCPETED_APPOINTMENTS = "CLEAR_ACCPETED_APPOINTMENTS" 
export const CLEAR_APPOINTMENT_ERROR_MESSAGES ="CLEAR_APPOINTMENT_ERROR_MESSAGES"

export const SET_USER = 'SET_USER'
export const LOG_FAILED = 'LOG_FAILED'
export const LOG_OUT = 'LOG_OUT'
export const FAILED_FETCH_USER_DATA = 'FAILED_FETCH_USER_DATA'

export const LOAD_CENTER_DAYS = 'LOAD_CENTER_DAYS'
export const LOADING_CENTER_DAYS = 'LOADING_CENTER_DAYS'
export const LOAD_CENTER_DAYS_FAILED = 'LOAD_CENTER_DAYS_FAILED'
export const ADD_WORKING_DAYS = 'ADD_WORKING_DAYS'
export const ADD_WORKING_DAYS_FAILED  = 'ADD_WORKING_DAYS_FAILED'
export const CLEAR_ERROR_MESSAGES = "CLEAR_ERROR_MESSAGES"
export const CLEAR_ERR_MESS = 'CLEAR_ERR_MESS' 
export const UPDATE_WORKING_DAY = 'UPDATE_WORKING_DAY'
export const DELETE_WORKING_DAY = 'DELETE_WORKING_DAY'
