const APPOINTMENTS = [{
    id: 1 ,
    day : 'Saturday',
    appointmentDate : '2021-05-20',
    startTime: '10:30',
    endTime: '10:30',
    title: 'headeach',
    description: 'i feel some illnesss in my headech',
    type :"Review",
    status: 'pending',
    doctorId: 2,
    patientId: 1,
    sessionId : 2,
    clinicId : 2
    
},
{
    id: 2 ,
    day : 'Saturday',
    appointmentDate : '2021-05-20',
    startTime: '12:30',
    endTime: '10:30',
    title: 'headeach',
    description: 'i feel some illnesss in my stomech',
    type :"Review",
    status: 'accepted',
    doctorId: 2,
    patientId: 2,
    sessionId : 2,
    clinicId : 2
},
{
    id: 3 ,
    day : 'Saturday',
    appointmentDate : '2021-05-20',
    startTime: '23:30',
    endTime: '10:30',
    title: 'headeach',
    description: 'i feel some illnesss in my touth',
    type :"Review",
    status: 'pending',
    doctorId: 2,
    patientId: 3,
    sessionId : 2,
    clinicId : 2
},
{
    id: 4 ,
    day : 'Saturday',
    appointmentDate : '2021-05-20',
    startTime: '09:00',
    endTime: '10:30',
    title: 'headeach',
    description: 'i feel some illnesss in my legs',
    type :"Review",
    status: 'pending',
    doctorId: 2,
    patientId: 4,
    sessionId : 2,
    clinicId : 2
}]
export default APPOINTMENTS