export const SESSIONS = [
    {
        id: 1,
        day: 'Saturday',
        date: '2021-05-20',
        description: 'i feel some illnesss in my headech',
        type: "Review",
        doctorName : "medhat",
    },
    {
        id: 2,
        day: 'Saturday',
        date: '2021-05-20',
        description: 'i feel some illnesss in my headech',
        type: "Review",
        doctorName : "medhat",
    },
    {
        id: 3,
        day: 'Saturday',
        date: '2021-05-20',
        description: 'i feel some illnesss in my headech',
        type: "Review",
        doctorName : "medhat",
    },
    {
        id: 4,
        day: 'Saturday',
        date: '2021-05-20',
        description: 'i feel some illnesss in my headech',
        type: "Review",
        doctorName : "medhat",
    },
    {
        id: 5,
        day: 'Saturday',
        date: '2021-05-20',
        description: 'i feel some illnesss in my headech',
        type: "Review",
        doctorName : "medhat",
    },
]